### ISSUE TITLE
Getting errors when I try and run afkbot.py

### ISSUE THREAD

**Issue by NebulaBC** [chuck-r/afkbot#1]
when I run any command with the afkbot.py I get
```
File "afkbot.py", line 101, in <module>
    messageLookupMessage={Mumble_pb2.Version:0,Mumble_pb2.UDPTunnel:1,Mumble_pb2.Authenticate:2,Mumble_pb2.Ping:3,Mumble_pb2.Reject:4,Mumble_pb2.ServerSync:5,
NameError: name 'Mumble_pb2' is not defined
```
and if I run with python3 I get 
```
File "afkbot.py", line 125
    print time.strftime("%a, %d %b %Y %H:%M:%S +0000"), "Received shutdown notice"
```
I am on Ubuntu 18.04 server

**Comment by NebulaBC** [comment]
Stopped using mumble and switched to matrix + this issue is old. Closing.

**Comment by chuck-r** [comment]
Sorry about not getting to this. The error you were getting was due to not having the protobuf python library installed, most likely. Apparently, the errors weren't working correctly to notify of that. I went ahead and updated the script to Python 3 and it works now. I'm glad you figured something out though.
